### ISSUE TITLE
dynamic label

### ISSUE THREAD

**Issue by MikkelNielsen1** [littlevgl/lv_boards#11]
Hi
how does you change the text dynamically in a label

**Comment by kisvegabor** [comment]
Hi,
With `lv_label_set_text(label1, "My text")`
More info here: https://littlevgl.com/object-types/label-lv_label

**Comment by MikkelNielsen1** [comment]
But how Can i change the text While the program is running?

**Comment by kisvegabor** [comment]
With the mentioned function. You call it as many time as you want in run time:
```c
 lv_label_set_text(label1, "72%");
 lv_label_set_text(label1, "76%");
 lv_label_set_text(label1, "71%");
```

Or if you have a cycle to refresh things, here is a stupid example:
```c
while(1) {
  value = read_something();
  char buf[32];
  num_to_str(value, buf);               //sprintf or something to convert the number to a string
  lv_label_set_text(label1, buf);
  delay_ms(100);
}


```
