### ISSUE TITLE
Error in real pc

### ISSUE THREAD

**Issue by huyhtc** [littlevgl/lv_boards#2]
hello,

when I run the GUI with the Linux frame buffer .
ubuntu  14.04.5 LTS 32BIT in virtualbox is OK, but, error in real pc(ubuntu  14.04.5 LTS 32BIT).

The Physical resolution is 1366X768 32bpp。

![img_3702](https://user-images.githubusercontent.com/7598889/37477585-fcebcc80-28b2-11e8-9306-8ff7ebd03a3f.JPG)

when i set 
#define LV_HOR_RES          (1366)
#define LV_VER_RES          (768)
it show like this
![img_3698](https://user-images.githubusercontent.com/7598889/37477641-2520833a-28b3-11e8-94b6-119b428ee71c.JPG)

Please help me find the reason, thank you very much!

**Comment by kisvegabor** [comment]
Hi,

It seems some the library sees wrong resolution. If you check carefully you can see the GUI but lines are shifted (The correct colors are there)

Please `printf` `vinfo.xres` and `vinfo.xres` in `fbdev_init`

**Comment by huyhtc** [comment]
Hi,

The first photo shows
1366x768, 32bpp

vinfo.xres = 1366
vinfo.yres = 768

The monitor 's Physical resolution is 1366X768 32bpp。
The second photo show when i set LV_HOR_RES (1366) and VER_RES (768).

**Comment by kisvegabor** [comment]
I see, thank you.

It seems to your frame buffer device is somehow wider or shorter then 1366 px that is why we skew lines.

To be sure it is the problem, please:
1. Comment out `lv_task_handler()`
2. Before the main while(1) call 
  - `fbdev_fill(0, 0, LV_HOR_RES, LV_VER_RES, LV_COLOR_BLACK)` to paint the screen black
  - `fbdev_fill(0, 0, 1, 100, LV_COLOR_RED)` to draw a pixel width vertical line

**Comment by huyhtc** [comment]
hi,
Anther PC,
It's Physical resolution is 1400X1050 32bpp.
The same error occurred.

it is not a  vertical line.
#define LV_HOR_RES          (320)
#define LV_VER_RES          (240)
![img](https://user-images.githubusercontent.com/7598889/37593816-4ebcb3f0-2bae-11e8-8612-89ed20479999.jpg)

**Comment by kisvegabor** [comment]
Thank you! This image tells a lot!

Please debug still two variables:
* vinfo,bits_per_pixel
* vinfo.xoffset

The problem should be in one of them

**Comment by huyhtc** [comment]
Hi,
vinfo.bits_per_pixel = 32
vinfo.xoffset = 0
vinfo.yoffset = 0

It Can display correctly after i add one line of code in function fbdev_init
The PC ( 1366x768 ) I add vinfo.xres += 10;
The PC (1400x1050 ) I add vinfo.xres += 8;

Thank you！

**Comment by kisvegabor** [comment]
Thank you.
I have no idea why is it required. All settings seems good.

Anyway thank you for the Debugging! In lack of a good solution I close this issue. If you have some news in this topic feel free to reopen it!

**Comment by huyhtc** [comment]
I guess,  vinfo.xres should be an integer multiple of 16.

**Comment by kisvegabor** [comment]
Maybe, but I never heard about something like this. And also didn't find anything about limitations in value. 

But I found this command: `sudo fbset`
More info here: https://www.systutorials.com/docs/linux/man/8-fbset/

It tells me: 
```
mode "1920x1080"
    geometry 1920 1080 1920 1080 32
    timings 0 0 0 0 0 0 0
    accel true
    rgba 8/16,8/8,8/0,0/0
endmode
```

**Comment by huyhtc** [comment]
mode "1366x768"
    geometry 1366 768 1366 768 32
    timings 0 0 0 0 0 0 0
    accel true
    rgba 8/16,8/8,8/0,0/0
endmode

**Comment by huyhtc** [comment]
hi
use 
sudo fbset -i

Frame buffer device information:
    Name        : inteldrmfb
    Address     : 0xc0000000
    Size        : 4227072
    Type        : PACKED PIXELS
    Visual      : TRUECOLOR
    XPanStep    : 1
    YPanStep    : 1
    YWrapStep   : 0
    LineLength  : 5504
    Accelerator : No

LineLength  : 5504  = 1376*4

**Comment by kisvegabor** [comment]
For me it's:
```c
mode "1920x1080"
    geometry 1920 1080 1920 1080 32
    timings 0 0 0 0 0 0 0
    accel true
    rgba 8/16,8/8,8/0,0/0
endmode

Frame buffer device information:
    Name        : inteldrmfb
    Address     : 0xa0084000
    Size        : 8294400
    Type        : PACKED PIXELS
    Visual      : TRUECOLOR
    XPanStep    : 1
    YPanStep    : 1
    YWrapStep   : 0
    LineLength  : 7680
    Accelerator : No
```

So 1920 * 4 = 7680

It seems the driver hold use the LineLength instead of `xres`

**Comment by huyhtc** [comment]
and 
4 = bits_per_pixel  / 8
so use LineLength  / (  bits_per_pixel  / 8 ) is better.
